events {}

http {
    default_type application/octet-stream;
    include /etc/nginx/mime.types;

    server {
        listen 3000;
        root /usr/share/nginx/html;

        
        gzip on;
        gzip_types text/html application/javascript application/json text/css;

        location / {
            try_files $uri $uri/ $uri.html /index.html;
        }

        location ~* \.(?:css|js|svg|jpg|png|webp|mp4|m4a|webm|ogg|opus)$ {
            expires 30d;
            add_header Cache-Control "public";
        }

        location ~* \.(?:json)$ {
            expires 1d;
            add_header Cache-Control "public";
        }
    }
}